In [2]:
import torch
import numpy as np

data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)

x_ones = torch.ones_like(x_data)   # 保留 x_data 的属性
print(f"Ones Tensor: \n {x_ones} \n")

x_rand = torch.rand_like(x_data, dtype=torch.float)   # 重写 x_data 的数据类型 int -> float

print(f"Random Tensor: \n {x_rand} \n")
tensor = torch.rand(3,4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

shape = (2,3)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")


Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.3254, 0.3740],
        [0.1888, 0.6137]]) 

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu
Random Tensor: 
 tensor([[0.8042, 0.6819, 0.3448],
        [0.7829, 0.2434, 0.0193]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [87]:
from torch.autograd import Variable
x = Variable(torch.ones(2, 2), requires_grad = True)
y = x +4

# y 是作为一个操作的结果创建的因此y有一个creator 
z = y * y
print(z)
# out =z.mean()
out =z

a=torch.FloatTensor([[1., 500.0000e+00],
        [2., 4.5914e-41]])
print(a)

out.backward(a)
print(x.grad)

tensor([[25., 25.],
        [25., 25.]], grad_fn=<MulBackward0>)
tensor([[1.0000e+00, 5.0000e+02],
        [2.0000e+00, 4.5914e-41]])
tensor([[1.0000e+01, 5.0000e+03],
        [2.0000e+01, 4.5914e-40]])


In [19]:
x = torch.randn(3)
x = Variable(x, requires_grad = True)
y = x * 2
while y.data.norm() < 1000:
    y = y * 2
gradients = torch.FloatTensor([0.1, 1.0, 0.0001])
y.backward(gradients)
x.grad

tensor([1.0240e+02, 1.0240e+03, 1.0240e-01])